apiVersion: v1
kind: Secret
metadata:
  name: microservices-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_HOST:        {{ required "global.db.host is required" .Values.global.db.host | quote }}
  DB_PORT:        {{ .Values.global.db.port | toString | quote }}
  DB_USER:        {{ required "global.db.user is required" .Values.global.db.user | quote }}
  DB_PASSWORD:    {{ required "global.db.password is required" .Values.global.db.password | quote }}
  JWT_SECRET:     {{ required "global.jwtSecret is required" .Values.global.jwtSecret | quote }}
